language: python

python:
  - "3.6"

before_install:
  - python --version
  - pip3 install -U pytest
  - pip3 install codecov

script:
  # testing code of exercicio-condicional folder
  -  python3 exercicio-condicional/questao-1.py < exercicio-condicional/questao-1.txt
  -  python3 exercicio-condicional/questao-2.py < exercicio-condicional/questao-2.txt
  -  python3 exercicio-condicional/questao-3.py < exercicio-condicional/questao-3.txt
  -  python3 exercicio-condicional/questao-4.py < exercicio-condicional/questao-4.txt

after_success:
  - codecov