language: python

python:
  - "3.6"

before_install:
  - python --version
  - pip3 install -U pytest
  - pip3 install codecov

script:
  # testing code of exercicio-condicional folder
  -  coverage run exercicio-condicional/questao-1.py < tests/exercicio-condicional-tests/questao-1.txt
  -  coverage run exercicio-condicional/questao-2.py < tests/exercicio-condicional-tests/questao-2.txt
  -  coverage run exercicio-condicional/questao-3.py < tests/exercicio-condicional-tests/questao-3.txt
  -  coverage run exercicio-condicional/questao-4.py < tests/exercicio-condicional-tests/questao-4.txt

  # testing code of lista-exercicio folder
  - coverage run lista-exercicio/questao-1.py
  - coverage run lista-exercicio/questao-2.py < tests/lista-exercicio-tests/questao-2.txt
  - coverage run lista-exercicio/questao-3.py < tests/lista-exercicio-tests/questao-3.txt
  - coverage run lista-exercicio/questao-4.py < tests/lista-exercicio-tests/questao-4.txt
  - coverage run lista-exercicio/questao-5.py < tests/lista-exercicio-tests/questao-5.txt
  - coverage run lista-exercicio/questao-6.py < tests/lista-exercicio-tests/questao-6.txt
  - coverage run lista-exercicio/questao-7.py < tests/lista-exercicio-tests/questao-7.txt
  - coverage run lista-exercicio/questao-8.py < tests/lista-exercicio-tests/questao-8.txt
  - coverage run lista-exercicio/questao-9.py < tests/lista-exercicio-tests/questao-9.txt
  - coverage run lista-exercicio/questao-10.py < tests/lista-exercicio-tests/questao-10.txt
  - coverage run lista-exercicio/questao-11.py < tests/lista-exercicio-tests/questao-11.txt
  - coverage run lista-exercicio/questao-12.py < tests/lista-exercicio-tests/questao-12.txt

  # testing code of lista-exercicio folder
  - coverage run projetos-rapidos/jokenpo-simples.py < tests/projetos-rapidos-tests/jokenpo-simples.txt
  - coverage run projetos-rapidos/jokenpo-final.py < tests/projetos-rapidos-tests/jokenpo-final.txt
  - coverage run projetos-rapidos/cryptoWord.py < tests/projetos-rapidos-tests/cryptoWord.txt
  - coverage run projetos-rapidos/cryptoWord.py < tests/projetos-rapidos-tests/cryptoMessage.txt

after_success:
  - codecov