language: python

python:
  - "3.6"

before_install:
  - python --version
  - pip3 install -U pytest
  - pip3 install codecov

script:
  # testing code of exercicio-condicional folder
  -  python3 exercicio-condicional/questao-1.py < tests/exercicio-condicional-tests/questao-1.txt
  -  python3 exercicio-condicional/questao-2.py < tests/exercicio-condicional-tests/questao-2.txt
  -  python3 exercicio-condicional/questao-3.py < tests/exercicio-condicional-tests/questao-3.txt
  -  python3 exercicio-condicional/questao-4.py < tests/exercicio-condicional-tests/questao-4.txt

  # testing code of lista-exercicio folder
  - python3 lista-exercicio/questao-1.py
  - python3 lista-exercicio/questao-2.py < tests/lista-exercicio-tests/questao-2.txt
  - python3 lista-exercicio/questao-3.py < tests/lista-exercicio-tests/questao-3.txt

after_success:
  - codecov